spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.177.54:3306/gzxant?useUnicode=true&characterEncoding=utf8
    username: gzxant.admin
    password: 2018gzxant